### ISSUE TITLE
[1.20.4] BUG: Crash with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [TheMCBrothers/UselessMod#33]
**Describe the bug**
Crash when starting the game

```
[20:48:33] [Render thread/ERROR] [ne.ne.fm.ja.FMLModContainer/]: Exception caught during firing event: 'net.minecraft.client.renderer.entity.LivingEntityRenderer net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers.getSkin(net.minecraft.client.resources.PlayerSkin$Model)'
	Index: 0
	Listeners:
		0: net.themcbrothers.uselessmod.setup.ClientSetup$$Lambda/0x0000758240f38c00@7b86b5d7
java.lang.NoSuchMethodError: 'net.minecraft.client.renderer.entity.LivingEntityRenderer net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers.getSkin(net.minecraft.client.resources.PlayerSkin$Model)'
	at TRANSFORMER/uselessmod@9.0.0/net.themcbrothers.uselessmod.setup.ClientSetup.entityAddLayers(ClientSetup.java:165)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:386)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:365)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:210)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.ModLoader.lambda$postEvent$29(ModLoader.java:346)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:231)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:346)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.renderer.entity.EntityRenderDispatcher.onResourceManagerReload(EntityRenderDispatcher.java:458)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.Minecraft.runTick(Minecraft.java:1223)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.Minecraft.run(Minecraft.java:818)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.main.Main.main(Main.java:244)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

[20:48:33] [Render thread/ERROR] [ne.ne.fm.ModContainer/LOADING]: Caught exception during event net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers@1d2be44d dispatch for modid uselessmod
java.lang.NoSuchMethodError: 'net.minecraft.client.renderer.entity.LivingEntityRenderer net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers.getSkin(net.minecraft.client.resources.PlayerSkin$Model)'
	at net.themcbrothers.uselessmod.setup.ClientSetup.entityAddLayers(ClientSetup.java:165) ~[uselessmod-1.20.4-9.0.0.jar%23211!/:9.0.0] {re:classloading}
	at net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-7.2.0.jar%23144!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%23144!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:365) ~[bus-7.2.0.jar%23144!/:?] {}
	at net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:210) ~[loader-2.0.11.jar%23136!/:2.0] {}
	at net.neoforged.fml.ModLoader.lambda$postEvent$29(ModLoader.java:346) ~[loader-2.0.11.jar%23136!/:2.0] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.neoforged.fml.ModList.forEachModInOrder(ModList.java:231) ~[loader-2.0.11.jar%23136!/:2.0] {}
	at net.neoforged.fml.ModLoader.postEvent(ModLoader.java:346) ~[loader-2.0.11.jar%23136!/:2.0] {}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.onResourceManagerReload(EntityRenderDispatcher.java:458) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.render.entity.shadows.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:15) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1223) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:goldenfoods.mixins.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:obsidianui.mixins.json:MinecraftClientMixin,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin,pl:mixin:APP:azurelib.neo.mixins.json:MinecraftMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin,pl:mixin:APP:ryoamiclights.common.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:818) ~[client-1.20.4-20231207.154220-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:goldenfoods.mixins.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:obsidianui.mixins.json:MinecraftClientMixin,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin,pl:mixin:APP:azurelib.neo.mixins.json:MinecraftMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin,pl:mixin:APP:ryoamiclights.common.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:244) ~[minecraft-1.20.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.11.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.11.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.11.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.11.jar:2.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

**Comment by TheMCCrazyMan** [comment]
Can you provide more information? Maybe the NeoForge Version? That would be nice

**Comment by Lolothepro** [comment]
NeoForge 20.4.183

**Comment by TheMCCrazyMan** [comment]
I just tried to recreate your issue. And for me it works, with the version 20.4.183. Can you provide more details, such as other mods that you have possibly installed?

**Comment by Lolothepro** [comment]
log: https://mclo.gs/fYPJuM6
Minecraft launches, but doesn't load

**Comment by TheMCLoveMan** [comment]
Reproduced using Modrinth launcher, with some other mods installed...

https://mclo.gs/9momwhR

**Comment by TheMCCrazyMan** [comment]
Okay after long research, we finally found a solution. Will be fixed in the next release. Thank you very much!
